### ISSUE TITLE
Question regarding module 6 assignment 3

### ISSUE THREAD

**Issue by sprinz11** [rbtl-fs24/project-sprinz11#1]
@larnsce 

For step 2.5: should the `data` folder be created inside the R folder?
My gut says no, but for 2.6 it is specified that the `docs` folder should be in the root folder.

Thanks for the clarification.
![grafik](https://github.com/rbtl-fs24/project-sprinz11/assets/114858201/17132bf0-4b6e-44e7-9217-4e8871b49adb)
That's how my root folder looks right now:
![grafik](https://github.com/rbtl-fs24/project-sprinz11/assets/114858201/9986f8b0-e736-407e-827d-3a796bf26cb3)

**Comment by larnsce** [comment]
Your gut was right. Thanks for poining this out, the description of the task will be improved for 2025.
